image: Visual Studio 2015
version: "1.0.0.{build}"
configuration:
  - Release

init:
  - git config --global core.autocrlf input
  - echo %APPVEYOR_BUILD_VERSION%

assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: '{version}'

test: off

before_build:
  - ps: .\Set-PackageLabel.ps1
  - dotnet restore -v minimal

build:
  project: UpdateVersionTest.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: .\CreatePackages.ps1

artifacts:
  - path: artifacts\*.nupkg