image: Visual Studio 2015
version: "1.0.0-development-{build}"
configuration:
  - Release

init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

test: off

before_build:
  - ps: .\Set-PackageLabel.ps1
  # if git tag = v{Maj}.{Min}.{Build}.{Revision} then use release feed else use CI feed
  - ps: $nugetSource = 'https://api.nuget.org/v3/index.json';
  - ps: $isRelease = $Env:APPVEYOR_REPO_TAG -eq $true -and $Env:APPVEYOR_REPO_TAG_NAME -match 'v(\d+(\.)?){1,4}';
  - ps: if($isRelease) { dotnet restore -v minimal -s $nugetSource } else { dotnet restore -v minimal -s $nugetSource }

before_build:
  - ps: .\Set-PackageLabel.ps1
  - dotnet restore -v minimal

build:
  project: parliament-services.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: .\CreatePackages.ps1

artifacts:
  - path: artifacts\*.nupkg